// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5eBPq-qZbjH8txJEiiYo0SsygUY_9Jm0',
    appId: '1:137876250697:web:e9f1d8382e1fbcfb2fdf98',
    messagingSenderId: '137876250697',
    projectId: 'banglahub-430ec',
    authDomain: 'banglahub-430ec.firebaseapp.com',
    storageBucket: 'banglahub-430ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOdMEeI3uZAS9NRFiPDOvgsFPJnqG782k',
    appId: '1:137876250697:android:4e4687bb45e69ce02fdf98',
    messagingSenderId: '137876250697',
    projectId: 'banglahub-430ec',
    storageBucket: 'banglahub-430ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfGQHs7gmdG8HCOYsR4eWXdwbZWIW6_7A',
    appId: '1:137876250697:ios:f620da898e83fde22fdf98',
    messagingSenderId: '137876250697',
    projectId: 'banglahub-430ec',
    storageBucket: 'banglahub-430ec.firebasestorage.app',
    iosClientId: '137876250697-tgp1kf8rvbmpi3etioo6ng30tineac82.apps.googleusercontent.com',
    iosBundleId: 'com.example.banglaHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfGQHs7gmdG8HCOYsR4eWXdwbZWIW6_7A',
    appId: '1:137876250697:ios:f620da898e83fde22fdf98',
    messagingSenderId: '137876250697',
    projectId: 'banglahub-430ec',
    storageBucket: 'banglahub-430ec.firebasestorage.app',
    iosClientId: '137876250697-tgp1kf8rvbmpi3etioo6ng30tineac82.apps.googleusercontent.com',
    iosBundleId: 'com.example.banglaHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5eBPq-qZbjH8txJEiiYo0SsygUY_9Jm0',
    appId: '1:137876250697:web:c6f5ad085054ca782fdf98',
    messagingSenderId: '137876250697',
    projectId: 'banglahub-430ec',
    authDomain: 'banglahub-430ec.firebaseapp.com',
    storageBucket: 'banglahub-430ec.firebasestorage.app',
  );
}
